//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaRepacker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_zh_CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh_CHS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaRepacker.Properties.Resources.zh-CHS", typeof(Resources_zh_CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的浏览器或照片查看器不支持此格式的动画, 请下载更新的浏览器比如火狐.
        /// </summary>
        public static string AnimCompatMessage {
            get {
                return ResourceManager.GetString("AnimCompatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at animation builder, frame {0}.
        /// </summary>
        public static string AnimError {
            get {
                return ResourceManager.GetString("AnimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Portable Network Graphics (*.png).
        /// </summary>
        public static string ApngFilter {
            get {
                return ResourceManager.GetString("ApngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立足点.
        /// </summary>
        public static string EditFoothold {
            get {
                return ResourceManager.GetString("EditFoothold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传送点.
        /// </summary>
        public static string EditPortal {
            get {
                return ResourceManager.GetString("EditPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 怪物召唤点.
        /// </summary>
        public static string EditSP {
            get {
                return ResourceManager.GetString("EditSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用自定义编码.
        /// </summary>
        public static string EncTypeCustom {
            get {
                return ResourceManager.GetString("EncTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruteforce AES密钥（生成）.
        /// </summary>
        public static string EncTypeGenerate {
            get {
                return ResourceManager.GetString("EncTypeGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global MapleStory (旧).
        /// </summary>
        public static string EncTypeGMS {
            get {
                return ResourceManager.GetString("EncTypeGMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新楓之谷 / 冒险岛Online / 메이플스토리 / MapleSEA/ EMS(旧).
        /// </summary>
        public static string EncTypeMSEA {
            get {
                return ResourceManager.GetString("EncTypeMSEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMS / GMS / MapleSEA / メイプルストーリー / 메이플스토리.
        /// </summary>
        public static string EncTypeNone {
            get {
                return ResourceManager.GetString("EncTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入有效的內容.
        /// </summary>
        public static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only available under the x86 version of HaRepacker, please get the alternative version..
        /// </summary>
        public static string ExecutingAssemblyError {
            get {
                return ResourceManager.GetString("ExecutingAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入无效.确定前请提供有效的值..
        /// </summary>
        public static string FHMapperInvalidInput {
            get {
                return ResourceManager.GetString("FHMapperInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to force值.
        /// </summary>
        public static string FHSettingsForceValue {
            get {
                return ResourceManager.GetString("FHSettingsForceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}无效.
        ///请在确定前确认所有的值都有效..
        /// </summary>
        public static string FHSettingsInvalidMessage {
            get {
                return ResourceManager.GetString("FHSettingsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next值.
        /// </summary>
        public static string FHSettingsNextValue {
            get {
                return ResourceManager.GetString("FHSettingsNextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传送点类型值.
        /// </summary>
        public static string FHSettingsPortalValue {
            get {
                return ResourceManager.GetString("FHSettingsPortalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prev值.
        /// </summary>
        public static string FHSettingsPrevValue {
            get {
                return ResourceManager.GetString("FHSettingsPrevValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X值.
        /// </summary>
        public static string FHSettingsXValue {
            get {
                return ResourceManager.GetString("FHSettingsXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y值.
        /// </summary>
        public static string FHSettingsYValue {
            get {
                return ResourceManager.GetString("FHSettingsYValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片 (*.jpg;*.bmp;*.png;*.gif;*.tiff).
        /// </summary>
        public static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the WZ encryption used:.
        /// </summary>
        public static string InteractionWzMapleVersionInfo {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ Encryption.
        /// </summary>
        public static string InteractionWzMapleVersionTitle {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增图片.
        /// </summary>
        public static string MainAddCanvas {
            get {
                return ResourceManager.GetString("MainAddCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增convex.
        /// </summary>
        public static string MainAddConvex {
            get {
                return ResourceManager.GetString("MainAddConvex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增目录.
        /// </summary>
        public static string MainAddDir {
            get {
                return ResourceManager.GetString("MainAddDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增双精度浮点数.
        /// </summary>
        public static string MainAddDouble {
            get {
                return ResourceManager.GetString("MainAddDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增浮点数.
        /// </summary>
        public static string MainAddFloat {
            get {
                return ResourceManager.GetString("MainAddFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增IMG.
        /// </summary>
        public static string MainAddImg {
            get {
                return ResourceManager.GetString("MainAddImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增整數.
        /// </summary>
        public static string MainAddInt {
            get {
                return ResourceManager.GetString("MainAddInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 门户类型：{0}.
        /// </summary>
        public static string MainAdditionalInfo_PortalType {
            get {
                return ResourceManager.GetString("MainAdditionalInfo_PortalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增连接路径.
        /// </summary>
        public static string MainAddLink {
            get {
                return ResourceManager.GetString("MainAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增空值.
        /// </summary>
        public static string MainAddNull {
            get {
                return ResourceManager.GetString("MainAddNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增无符号短整数.
        /// </summary>
        public static string MainAddShort {
            get {
                return ResourceManager.GetString("MainAddShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增音乐.
        /// </summary>
        public static string MainAddSound {
            get {
                return ResourceManager.GetString("MainAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增文本.
        /// </summary>
        public static string MainAddString {
            get {
                return ResourceManager.GetString("MainAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增子目录.
        /// </summary>
        public static string MainAddSub {
            get {
                return ResourceManager.GetString("MainAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tab.
        /// </summary>
        public static string MainAddTabTitle {
            get {
                return ResourceManager.GetString("MainAddTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增坐标.
        /// </summary>
        public static string MainAddVec {
            get {
                return ResourceManager.GetString("MainAddVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法插入这个类型到选中的wz节点.
        /// </summary>
        public static string MainCannotInsertToNode {
            get {
                return ResourceManager.GetString("MainCannotInsertToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定你想终止当前操作?.
        /// </summary>
        public static string MainConfirmAbort {
            get {
                return ResourceManager.GetString("MainConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要将WZ节点复制到剪切板吗? (警告 - 如果选择的节点较多会花比较多时间).
        /// </summary>
        public static string MainConfirmCopy {
            get {
                return ResourceManager.GetString("MainConfirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定要离开吗?.
        /// </summary>
        public static string MainConfirmExit {
            get {
                return ResourceManager.GetString("MainConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要从剪切板粘贴WZ节点吗? (警告 - 如果选择的节点较多会花比较多时间).
        /// </summary>
        public static string MainConfirmPaste {
            get {
                return ResourceManager.GetString("MainConfirmPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定要删除这个节点吗?.
        /// </summary>
        public static string MainConfirmRemove {
            get {
                return ResourceManager.GetString("MainConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定你要删除当前节点吗?.
        /// </summary>
        public static string MainConfirmRemoveNode {
            get {
                return ResourceManager.GetString("MainConfirmRemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改名.
        /// </summary>
        public static string MainConfirmRename {
            get {
                return ResourceManager.GetString("MainConfirmRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法将&quot;{0}&quot;转换成需要的类型.
        /// </summary>
        public static string MainConversionError {
            get {
                return ResourceManager.GetString("MainConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法复制目录因为需要太多内存了.
        /// </summary>
        public static string MainCopyDirError {
            get {
                return ResourceManager.GetString("MainCopyDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开開WZ文件 &quot;{0}&quot;.
        /// </summary>
        public static string MainCouldntOpenWZ {
            get {
                return ResourceManager.GetString("MainCouldntOpenWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入{0} .img文件时出错。 你确定你选择了正确的WZ加密吗？.
        /// </summary>
        public static string MainErrorImportingWzImageFile {
            get {
                return ResourceManager.GetString("MainErrorImportingWzImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open/save to the specified file path. Please run as an Administrator instead..
        /// </summary>
        public static string MainFileOpenFail {
            get {
                return ResourceManager.GetString("MainFileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法显示帮助, 因为找不到帮助文件({0}).
        /// </summary>
        public static string MainHelpOpenFail {
            get {
                return ResourceManager.GetString("MainHelpOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法读取图片.
        /// </summary>
        public static string MainImageLoadError {
            get {
                return ResourceManager.GetString("MainImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件&quot;{0}&quot;&quot;无效, 将跳过。 错误: {1}.
        /// </summary>
        public static string MainInvalidFileError {
            get {
                return ResourceManager.GetString("MainInvalidFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个文件(路径: {0}) 是List.wz文件, 将会被跳过.
        /// </summary>
        public static string MainListWzDetected {
            get {
                return ResourceManager.GetString("MainListWzDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个名称的节点已存在, 请输入一个不同的节点名称.
        /// </summary>
        public static string MainNodeExists {
            get {
                return ResourceManager.GetString("MainNodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定要重载所有文件吗?.
        /// </summary>
        public static string MainReloadAll {
            get {
                return ResourceManager.GetString("MainReloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择WZ文件来保存.
        /// </summary>
        public static string MainSelectWzFolder {
            get {
                return ResourceManager.GetString("MainSelectWzFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a parent WzFile to add this WzDirectoryProperty..
        /// </summary>
        public static string MainTreeAddDirError {
            get {
                return ResourceManager.GetString("MainTreeAddDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经到达结尾了.
        /// </summary>
        public static string MainTreeEnd {
            get {
                return ResourceManager.GetString("MainTreeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定要关闭所有文件吗?.
        /// </summary>
        public static string MainUnloadAll {
            get {
                return ResourceManager.GetString("MainUnloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///點選 \&quot;確認\&quot; 下載新版本..
        /// </summary>
        public static string MainUpdateAvailable {
            get {
                return ResourceManager.GetString("MainUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新版本.
        /// </summary>
        public static string MainUpdateTitle {
            get {
                return ResourceManager.GetString("MainUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出目录未找到。 请在工具 - &gt;选项下指定它.
        /// </summary>
        public static string MainWzExportError {
            get {
                return ResourceManager.GetString("MainWzExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to include the base64 data of image, mp3 &amp; other binary data in the json?.
        /// </summary>
        public static string MainWzExportJson_IncludeBase64 {
            get {
                return ResourceManager.GetString("MainWzExportJson_IncludeBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string MainWzExportJson_IncludeBase64_Title {
            get {
                return ResourceManager.GetString("MainWzExportJson_IncludeBase64_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-1 Audio Layer 3 (*.mp3).
        /// </summary>
        public static string Mp3Filter {
            get {
                return ResourceManager.GetString("Mp3Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩进必须大于或等于0.
        /// </summary>
        public static string OptionsIndentError {
            get {
                return ResourceManager.GetString("OptionsIndentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 天前.
        /// </summary>
        public static string RelativeTime_DaysAgo {
            get {
                return ResourceManager.GetString("RelativeTime_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 小时前.
        /// </summary>
        public static string RelativeTime_HoursAgo {
            get {
                return ResourceManager.GetString("RelativeTime_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 分钟前.
        /// </summary>
        public static string RelativeTime_MinutesAgo {
            get {
                return ResourceManager.GetString("RelativeTime_MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 月前.
        /// </summary>
        public static string RelativeTime_MonthsAgo {
            get {
                return ResourceManager.GetString("RelativeTime_MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 秒前.
        /// </summary>
        public static string RelativeTime_SecondsAgo {
            get {
                return ResourceManager.GetString("RelativeTime_SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 年前.
        /// </summary>
        public static string RelativeTime_YearsAgo {
            get {
                return ResourceManager.GetString("RelativeTime_YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节点&quot;{0}&quot;已存在, 你想取代它吗?.
        /// </summary>
        public static string ReplaceConfirm {
            get {
                return ResourceManager.GetString("ReplaceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本必须大于或等于0.
        /// </summary>
        public static string SaveVersionError {
            get {
                return ResourceManager.GetString("SaveVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择默认XML文件夹.
        /// </summary>
        public static string SelectDefaultXmlFolder {
            get {
                return ResourceManager.GetString("SelectDefaultXmlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇圖片.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中类型: {0}.
        /// </summary>
        public static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇MP3文件.
        /// </summary>
        public static string SelectMp3 {
            get {
                return ResourceManager.GetString("SelectMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择动画路径.
        /// </summary>
        public static string SelectOutApng {
            get {
                return ResourceManager.GetString("SelectOutApng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择输出目录.
        /// </summary>
        public static string SelectOutDir {
            get {
                return ResourceManager.GetString("SelectOutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选着要储存的文件.
        /// </summary>
        public static string SelectOutWz {
            get {
                return ResourceManager.GetString("SelectOutWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择XML路径.
        /// </summary>
        public static string SelectOutXml {
            get {
                return ResourceManager.GetString("SelectOutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择WZ文件.
        /// </summary>
        public static string SelectWz {
            get {
                return ResourceManager.GetString("SelectWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择IMG文件.
        /// </summary>
        public static string SelectWzImg {
            get {
                return ResourceManager.GetString("SelectWzImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择XML文件.
        /// </summary>
        public static string SelectXml {
            get {
                return ResourceManager.GetString("SelectXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请稍等.
        /// </summary>
        public static string Subpanel_Loading {
            get {
                return ResourceManager.GetString("Subpanel_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ文件 (*.wz).
        /// </summary>
        public static string WzFilter {
            get {
                return ResourceManager.GetString("WzFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ 图像文件 (*.img).
        /// </summary>
        public static string WzImgFilter {
            get {
                return ResourceManager.GetString("WzImgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXtended Markup Language (*.xml).
        /// </summary>
        public static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
    }
}
